language: ruby
branches:
  only:
  - master
before_script:
  - chmod +x ./script/cibuild
script: ./script/cibuild
exclude: [vendor]
sudo: false
after_success:
  - bash <(curl -s https://codecov.io/bash)

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   on:
#     branch: master
  

